services:
  c1_imports:
    image: ghcr.io/mdbv/c1_imports:latest
    hostname: c1_imports
    env_file:
      - .env
    volumes:
      - data:/app/files
    restart: unless-stopped
  filegator:
    image: filegator/filegator:latest
    restart: always
    volumes:
      - data:/var/www/filegator/repository
      - private:/var/www/filegator/private
volumes:
  data:
  private:
